package com.schwab.nms.domain.enums;

public enum AuditAction {
    NOTIFICATION_ACCEPTED,
    NOTIFICATION_REJECTED,
    DUPLICATE_SUPPRESSED,
    ROUTING_DECISION_MADE,
    DELIVERY_QUEUED,
    DELIVERY_ATTEMPTED,
    DELIVERY_SUCCEEDED,
    DELIVERY_FAILED,
    RETRY_SCHEDULED,
    DELIVERY_ABANDONED,
    NOTIFICATION_EXPIRED,
    NOTIFICATION_ACKNOWLEDGED,
    NOTIFICATION_ESCALATED
}
